
library(caret)
library(mltools)
library(data.table)
dataset <- read.csv('C:\\Users\\parth\\OneDrive\\Documents\\UT Austin\\Intro to ML\\Group Project\\Bike-Sharing-Dataset\\hour.csv')
head(dataset)
dataset$season<-as.factor(dataset$season)
dataset$yr<-as.factor(dataset$yr)
dataset$mnth<-as.factor(dataset$mnth)
dataset$hr<-as.factor(dataset$hr)
dataset$holiday<-as.factor(dataset$holiday)
dataset$weekday<-as.factor(dataset$weekday)
dataset$workingday<-as.factor(dataset$workingday)
dataset$weathersit<-as.factor(dataset$weathersit)
df<-as.data.table(dataset)
df<-one_hot(as.data.table(df))
